language: ruby

rvm:
  - 2.2.10
  - 2.5.9
  - 2.7.4
  - 3.0.0

env:
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.2
  - RAILS_VERSION=6.0
  - RAILS_VERSION=6.1

jobs:
  exclude:
    - rvm: 2.2.10
      env: RAILS_VERSION=5.2
    - rvm: 2.2.10
      env: RAILS_VERSION=6.0
    - rvm: 2.2.10
      env: RAILS_VERSION=6.1

    - rvm: 2.5.9
      env: RAILS_VERSION=4.2

    - rvm: 2.7.4
      env: RAILS_VERSION=4.2

    - rvm: 3.0.0
      env: RAILS_VERSION=4.2
    - rvm: 3.0.0
      env: RAILS_VERSION=5.2
    - rvm: 3.0.0
      env: RAILS_VERSION=6.0

before_install:
  - gem install bundler -v 1.15

script: bundle exec rspec
